# playinmpv
A server to support playing videos with mpv, which is suitable for bilibili.com based on Tampermonkey-script [[https://github.com/the1812/Bilibili-Evolved][Bilibili-Evolved]] .
It could be easily installed by =pip=.

* Installation
1. Install [[https://www.python.org/downloads/][Python3]]/(>=3.8)/ and =pip=
2. Run =pip install playwithmpv --user=

Maybe you want to use it to watch Bilibili vidoes, and you should do more -- Install some useful tools.
* Preparation
1. Install [[https://mpv.io/installation/][MPV]] or [[https://github.com/hooke007/MPV_lazy][MPV_lazy]] /(Amazing!)/
2. Use mpv command line to play video url /(Prepare and test it works, maybe you should install some lib)/
3. Install  [[https://github.com/the1812/Bilibili-Evolved][Bilibili-Evolved]] /(Also amazing)/
4. Install “下载视频” 组件
5. Install mpv-output-playlist 插件

* Usage
1. Run =playwithmpv= in console/terminal, which would start a server. (default =http://127.0.0.1:50000=)
2. 打开"下载视频“界面，"输出方式“中选择“MPV播放”，需配置mpv命令路径/（如果路径已加入环境变量，就不用改了）/，主机和端口默认是配置好的（ =http://127.0.0.1:50000=）
3. Click "播放“. Actually MPV open a play list, and you can watch the expected eposide.

* BTW
Mpv is a so strong and free tool that can be easily used for many amazing files,
for instance, stream-video(no-download), free customization, amazing plugins and move enhacement support etc.
